version: '3.8'

services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:0.6.2
    volumes:
      - type: volume
        source: mer-chroma-db
        target: /chroma/chroma

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/risk_tool
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=risk_tool
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "--password=password" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  mer-chroma-db:
