"""Initial migration

Revision ID: 17bf65762987
Revises: 3920e8618c28
Create Date: 2024-11-13 18:08:02.576081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17bf65762987'
down_revision: Union[str, None] = '3920e8618c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measures', sa.Column('risk_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'measures', 'risks', ['risk_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'measures', type_='foreignkey')
    op.drop_column('measures', 'risk_id')
    # ### end Alembic commands ###
