"""Initial migration

Revision ID: a48301ace15d
Revises: c779c33f734e
Create Date: 2024-11-13 18:05:28.217121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a48301ace15d'
down_revision: Union[str, None] = 'c779c33f734e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_measures')
    op.drop_index('ix_mappings_id', table_name='mappings')
    op.drop_table('mappings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mappings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('risk_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('measure_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measures.id'], name='mappings_ibfk_2'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], name='mappings_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_mappings_id', 'mappings', ['id'], unique=False)
    op.create_table('risk_measures',
    sa.Column('risk_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('measure_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['measure_id'], ['measures.id'], name='risk_measures_ibfk_2'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], name='risk_measures_ibfk_1'),
    sa.PrimaryKeyConstraint('risk_id', 'measure_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
