"""Initial migration

Revision ID: fe1b5a684e14
Revises: 86555293a85f
Create Date: 2024-11-13 18:29:50.379030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1b5a684e14'
down_revision: Union[str, None] = '86555293a85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mappings', sa.Column('scoring_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mappings', 'scorings', ['scoring_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mappings', type_='foreignkey')
    op.drop_column('mappings', 'scoring_id')
    # ### end Alembic commands ###
